# Simplest Python base image
FROM python:3.8-slim

# Set working directory inside the container
WORKDIR /app

# Copy current folder contents into /app in container
COPY . /app

# Command to run when the container starts
CMD ["python3", "myapp.py"]
